INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Csepel, Szent Imre tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Széll Kálmán tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Bikás park', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kelenföld vasútállomás', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kelenföld vasútállomás M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Batthyány tér M+H', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Újpalota, Nyírpalota út', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Móricz Zsigmond körtér M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kistarcsa, kórház', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Örs vezér tere', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mexikói út M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Cinkota, Lassú utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Ilonatelep', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Rákóczi tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Megyer, Szondi utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Aquincum', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Örs vezér tere M+H', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Opera', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Svábhegy', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Puskás Ferenc stadion', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szentjakab', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Bajcsy-Zsilinszky út', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Hõsök tere', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('II. János Pál pápa tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kodály körönd', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Sashalom', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Budakalász, Lenfonó', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szépvölgyi út', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Batthyány tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Széll Kálmán tér M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gödöllõ, Erzsébet park', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Arany János utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kaszásdûlõ', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Csepel, Csillagtelep', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mátyásföld, Imre utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kõbánya-Kispest', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mexikói út', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Boráros tér H', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gyöngyösi utca M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mogyoród', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Tímár utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Nyugati pályaudvar M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szent Gellért tér - Mûegyetem', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pasaréti tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Göncz Árpád városközpont', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Deák Ferenc tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Békásmegyer', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Hûvösvölgy', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Péterimajor', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Semmelweis Klinikák', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Nagytétény-Diósd vasútállomás', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Budakalász', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szentistvántelep', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mátyásföld, repülõtér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gödöllõ', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szilasliget', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mátyásföld alsó', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Nagyvárad tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Széchenyi fürdõ', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szentlélek tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Móricz Zsigmond körtér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kõbánya alsó vasútállomás', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Filatorigát', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Határ út', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Keleti pályaudvar M', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Rákospalota', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Árpádföld', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Dísz tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szebeni utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Göncz Árpád városközpont M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Cinkota alsó', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Forgách utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szent Imre tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Budatétény vasútállomás (Campona)', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Ferenciek tere', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Karácsony Sándor utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gyál', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Astoria', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Nyugati pályaudvar', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Keleti pályaudvar', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Vörösmarty tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Ecseri út', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Cinkotai autóbuszgarázs', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Közvágóhíd', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pestszentimre', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gödöllõ, Szabadság tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Nagyicce', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Rákosfalva', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Blaha Lujza tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Újbuda-központ', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kistarcsa', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Oktogon', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szentlélek tér H', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Nagybányai út', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Vecsési út', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szigetszentmiklós, városháza', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Deák Ferenc tér M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Margit híd, budai hídfõ', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Normafa', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Centenáriumi lakótelep', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kissvábhegy', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Káposztásmegyer, Szilas-patak', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gazdagréti tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Dózsa György út', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szentendre', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Újpest-Városkapu', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Újpest-központ M', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Budaörsi lakótelep', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Déli pályaudvar', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Csepel', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Boráros tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Lakihegy, Cseresznyés utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szentlõrinci úti lakótelep', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Lehel tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Cinkota', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Fõvám tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Blaha Lujza tér M', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Vörösmarty utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Csillaghegy', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mindszenty József bíboros tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kén utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Bajza utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Újpest-Központ', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Budakeszi, Dózsa György tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Diósd, Búzavirág utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Rákoskeresztúr', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szabadkikötõ', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szabadságtelep', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Zsófialiget', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pestszentlõrinc vasútállomás', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kerepes', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Óbuda, Bogdáni út', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Békásmegyer, Újmegyeri tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kossuth utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Káposztásmegyer, Mogyoródi-patak', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pannóniatelep', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pöttyös utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Hungexpo', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pesterzsébet felsõ', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gödöllõ, Palotakert', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Építész utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Margitsziget', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pillangó utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Újbuda-központ M', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kálvin tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Corvin-negyed', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Budakeszi, Tesco áruház', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Sánc utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Rómaifürdõ', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gyöngyösi utca', True);
