INSERT INTO Jármû (név, akadálymentes) VALUES ('Nagyvárad tér', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Bikás park', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Mexikói út', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Déli pályaudvar', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Batthyány tér', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Nyugati pályaudvar', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Széll Kálmán tér', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Móricz Zsigmond körtér', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Göncz Árpád városközpont', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Gyöngyösi utca', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Rákóczi tér', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Keleti pályaudvar', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Népliget', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Astoria', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Kodály körönd', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Bajza utca', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Kálvin tér', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Újbuda-központ', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Hõsök tere', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Semmelweis Klinikák', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Puskás Ferenc stadion', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Blaha Lujza tér', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Kelenföld vasútállomás', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Örs vezér tere', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Széchenyi fürdõ', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Pillangó utca', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Deák Ferenc tér', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Oktogon', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Határ út', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Ecseri út', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Arany János utca', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Opera', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Corvin-negyed', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Bajcsy-Zsilinszky út', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Ferenciek tere', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Forgách utca', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Fõvám tér', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Lehel tér', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Kõbánya-Kispest', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Újpest-Városkapu', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Vörösmarty tér', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Dózsa György út', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('II. János Pál pápa tér', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Pöttyös utca', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Újpest-Központ', True);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Szent Gellért tér - Mûegyetem', False);
INSERT INTO Jármû (név, akadálymentes) VALUES ('Vörösmarty utca', True);
