INSERT INTO Megálló (név, akadálymentes) VALUES ('Karácsony Sándor utca', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Déli pályaudvar', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Pöttyös utca', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Ecseri út', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Cinkota', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Mexikói út', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Kistarcsa', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Gödöllõ, Erzsébet park', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Vörösmarty tér', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Határ út', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Szentlélek tér', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Békásmegyer', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Szent Gellért tér - Mûegyetem', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Nyugati pályaudvar', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Pesterzsébet felsõ', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Fõvám tér', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Csepel', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Margit híd, budai hídfõ', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Örs vezér tere', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Kálvin tér', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Pannóniatelep', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Szentendre', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Lehel tér', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Puskás Ferenc stadion', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Pillangó utca', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Forgách utca', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Tímár utca', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Deák Ferenc tér', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Közvágóhíd', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Göncz Árpád városközpont', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Szépvölgyi út', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Csillaghegy', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Mogyoród', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Bikás park', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Pomáz', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Dózsa György út', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Semmelweis Klinikák', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Batthyány tér', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Bajza utca', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Újbuda-központ', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Budakalász', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Móricz Zsigmond körtér', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Csömör', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Széchenyi fürdõ', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Gödöllõ, Szabadság tér', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Rómaifürdõ', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Mátyásföld, Imre utca', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Szabadkikötõ', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Boráros tér', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Szentistvántelep', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Mátyásföld alsó', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Mátyásföld, repülõtér', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Vörösmarty utca', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Ferenciek tere', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Keleti pályaudvar', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Ilonatelep', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Kelenföld vasútállomás', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Szilasliget', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Filatorigát', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Hõsök tere', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Gödöllõ', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Astoria', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Szentjakab', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Oktogon', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Szent Imre tér', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Rákosfalva', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Újpest-Központ', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Kistarcsa, kórház', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Széll Kálmán tér', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Arany János utca', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Zsófialiget', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Rákóczi tér', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Kõbánya-Kispest', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Kaszásdûlõ', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Gyöngyösi utca', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Corvin-negyed', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Szabadságtelep', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Blaha Lujza tér', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Kén utca', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Újpest-Városkapu', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Cinkota alsó', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Gödöllõ, Palotakert', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Kerepes', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Népliget', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Nagyicce', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Opera', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Budakalász, Lenfonó', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Müpa – Nemzeti Színház ', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('II. János Pál pápa tér', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Sashalom', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Árpádföld', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Bajcsy-Zsilinszky út', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Kodály körönd', True);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Aquincum', False);
INSERT INTO Megálló (név, akadálymentes) VALUES ('Nagyvárad tér', True);
