INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Ecseri út', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Lehel tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Oktogon', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Széll Kálmán tér M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Káposztásmegyer, Szilas-patak', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Széll Kálmán tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Újpalota, Nyírpalota út', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kelenföld vasútállomás M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Svábhegy', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Örs vezér tere M+H', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Batthyány tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Keleti pályaudvar M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Keleti pályaudvar', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Bajza utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mexikói út', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Centenáriumi lakótelep', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Puskás Ferenc stadion', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Cinkota alsó', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Csepel, Szent Imre tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Batthyány tér M+H', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pomáz', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Rákóczi tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Boráros tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Móricz Zsigmond körtér M', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szentlélek tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Dózsa György út', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Müpa – Nemzeti Színház ', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Cinkota', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Újpest-Városkapu', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Békásmegyer', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mindszenty József bíboros tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Csepel, Csillagtelep', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Nagybányai út', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Margitsziget', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Margit híd, budai hídfő', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Arany János utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Örs vezér tere', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szigetszentmiklós, városháza', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Fővám tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szabadságtelep', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gödöllő, Szabadság tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Péterimajor', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pestszentimre', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Aquincum', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Albertfalva vasútállomás', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kistarcsa', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kodály körönd', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Újpest-központ M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Csillaghegy', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kelenföld vasútállomás', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kissvábhegy', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Tímár utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Blaha Lujza tér M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szentjakab', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pasaréti tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Nyugati pályaudvar', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Árpádföld', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pestszentlőrinc vasútállomás', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Normafa', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Astoria', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Budakalász', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Rákosfalva', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Diósd, Sashegyi út', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mexikói út M', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Káposztásmegyer, Mogyoródi-patak', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Építész utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szentlélek tér H', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Diósd, Búzavirág utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Sánc utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Békásmegyer, Újmegyeri tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kálvin tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mátyásföld, repülőtér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gödöllő, Erzsébet park', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gödöllő, Palotakert', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Boráros tér H', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Blaha Lujza tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Deák Ferenc tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Újpest-Központ', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Budaörsi lakótelep', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Göncz Árpád városközpont M', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Újbuda-központ', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Megyer, Szondi utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Filatorigát', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Semmelweis Klinikák', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Cinkota, Lassú utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Móricz Zsigmond körtér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kerepes', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kén utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Opera', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szent Imre tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Bajcsy-Zsilinszky út', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Corvin-negyed', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Rákospalota', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pöttyös utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Budakeszi, Tesco áruház', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pesterzsébet felső', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szentistvántelep', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Budakalász, Lenfonó', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Budakeszi, Dózsa György tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pannóniatelep', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kistarcsa, kórház', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Nagyvárad tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Hősök tere', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Bikás park', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Hungexpo', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Rákoskeresztúr', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szebeni utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Sashalom', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Karácsony Sándor utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gyöngyösi utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Nagytétény-Diósd vasútállomás', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Forgách utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Zsófialiget', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Hűvösvölgy', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Vörösmarty utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szépvölgyi út', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szent Gellért tér - Műegyetem', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('II. János Pál pápa tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Budatétény vasútállomás (Campona)', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szentendre', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Göncz Árpád városközpont', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Népliget', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Lakihegy, Cseresznyés utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szabadkikötő', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Újbuda-központ M', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gyöngyösi utca M', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Vecsési út', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gyál', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Dísz tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kőbánya-Kispest', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mátyásföld, Imre utca', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kossuth utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Határ út', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gazdagréti tér', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Csömör', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Ferenciek tere', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mátyásföld alsó', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Mogyoród', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Kaszásdűlő', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Csepel', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Ilonatelep', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Pillangó utca', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Déli pályaudvar', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Deák Ferenc tér M', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Óbuda, Bogdáni út', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Szentlőrinci úti lakótelep', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Cinkotai autóbuszgarázs', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Vörösmarty tér', True);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Gödöllő', False);
INSERT INTO Megálló (név, akadalymentesitett) VALUES ('Nyugati pályaudvar M', False);
